version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Make sure the Dockerfile is in the same directory
    hostname: tastyrhodos
    ports:
      - 8080:80  # Expose port 8080 for local access
    environment:
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=tastyigniter
      - DB_USERNAME=tastyigniter
      - DB_PASSWORD=somepassword
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
    volumes:
      - ../app:/var/www/html        # Bind mount app folder to container
      - ../data/storage:/var/www/html/storage  # Bind mount storage folder
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: mariadb:10.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tastyigniter
      - MYSQL_USER=tastyigniter
      - MYSQL_PASSWORD=somepassword
    volumes:
      - ./data/db:/var/lib/mysql  # Persistent DB storage
    ports:
      - 3306:3306  # Expose DB on port 3306
    restart: unless-stopped

  redis:
    image: redis:6
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - ./data/redis:/data  # Redis persistent storage
    restart: unless-stopped

volumes:
  app-data:
  db-data:
  redis-data:
